services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - /media/books:/srv
      - /media/container-storage/filebrowser/filebrowser.db:/database/filebrowser.db
      - /media/container-storage/filebrowser/settings.json:/config/settings.json
