services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - /media/books:/srv
      - /media/container-storage/filebrowser/filebrowser:/database
      - /media/container-storage/filebrowser/filebrowser:/config

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "9443:443"
    volumes:
      - /media/container-storage/filebrowser/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /media/container-storage/filebrowser/caddy/data:/data
      - /media/container-storage/filebrowser/caddy/config:/config
